// Shared print palette derived from the BIRW website light theme.
export const PDF_COLORS = {
  background: "#f6faf6",
  surface: "#ffffff",
  text: "#102017",
  mutedText: "#33443a",
  headerText: "#063f20",
  sectionText: "#075b78",
  primary: "#126a35",
  accent: "#c99a18",
  border: "#d3e3d7",
  tableHeader: "#eaf5ec",
  rowAlt: "#f6faf6",
  successFill: "#eaf5ec",
  successBorder: "#126a35",
  infoFill: "#eaf4ef",
  infoBorder: "#0b7da6",
  warningFill: "#fff6df",
  warningBorder: "#c99a18",
  dangerFill: "#fde9ea",
  dangerBorder: "#d36b78",
  neutralFill: "#eef6ef",
  neutralBorder: "#d3e3d7",
} as const
